Repository CleverCloud/doc.clever-cloud.com, pull requests merged in 2021-05, with the labels that each got.

#576 Help text when logs drain is disabled
  administrate/log-management.md
Labels: enhancement

#593 Format PHP language specific partial
  partials/language-specific-deploy/php.md
Labels: enhancement

#574 Help text when Github repository is not shown
  getting-started/quickstart.md
Labels: enhancement

#578 Add access logs section
  administrate/log-management.md
Labels: enhancement

#599 FAQ: Update wkhtmltopdf section
  find-help/faq.md
Labels: enhancement

#598 Replace plans with smart component
  deploy/addon/cellar.md
  deploy/addon/elastic.md
  deploy/addon/fs-bucket.md
  deploy/addon/mongodb.md
  deploy/addon/mysql/mysql.md
  deploy/addon/postgresql.md
  deploy/addon/redis.md
Labels: enhancement

#597 Format Python language specific partial
  deploy/application/python/tutorials/python-django-sample.md
  deploy/application/python/tutorials/python-flask-sample-app.md
  partials/cached-dependencies.md
  partials/language-specific-deploy/python.md
Labels: enhancement

#592 Install composer development deps from env
  partials/language-specific-deploy/php.md
  reference/reference-environment-variables.md
Labels: feature

#571 DOCKER: Add CC_DOCKERFILE / Private registry
  partials/language-specific-deploy/docker.md
  reference/reference-environment-variables.md
Labels: enhancement, feature

#513 Add new jvm metrics
  administrate/metrics/overview.md
Labels: enhancement
